"""Medical NLP data and models"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/65_medical.text.ipynb.

# %% auto #0
__all__ = []

# %% ../../nbs/65_medical.text.ipynb #c395b4a5
from ..basics import *
